"""
Color Configuration File for Room Identification

This file was auto-generated by extract_colors.py
You can manually edit it to add/remove colors.
"""

# Room color mappings
ROOM_COLORS = {
    "balcony": [
        "#6b8e23",  # RGB: (107, 142, 35) (found 16 times)
        (107, 142, 35),  # Same as #6b8e23
    ],

    "master bedroom": [
        "#ffa500",  # RGB: (255, 165, 0) (found 20 times)
        (255, 165, 0),  # Same as #ffa500
    ],

    "bathroom": [
        "#add8e6",  # RGB: (173, 216, 230) - Light blue
        (173, 216, 230),  # Same as #add8e6
    ],

    "common room": [
        "#ffd700",  # RGB: (255, 215, 0) (found 19 times)
        (255, 215, 0),  # Same as #ffd700
    ],

    "living room": [
        "#eee8aa",  # RGB: (238, 232, 170) (found 20 times)
        (238, 232, 170),  # Same as #eee8aa
    ],

    "kitchen": [
        "#f08080",  # RGB: (240, 128, 128) (found 20 times)
        (240, 128, 128),  # Same as #f08080
    ],

}